### PR TITLE
Update to cms 11

### PR DESCRIPTION
**Pull request by nolmsted**
Update nuget packages to cms 11
Move CategoriesSearchProvider into it's own project to follow Episerver's decoupling of search.
Change UiHint from obseleted value
Add nuspec files for EpiCategories.Find and EpiCategories.Search

### CODE REVIEW

**Comment by Codecamv** [comment]
+1 approved

**Comment by saintjon** [comment]
+1

**Comment by Codecamv** [comment]
Project dead? @MattisOlsson @degborta

**Comment by MattisOlsson** [comment]
Sorry for delay @Codecamv @nolmsted. I will review this tomorrow and do the merge.

**Comment by Codecamv** [comment]
Excellent, thank you!

**Comment by MattisOlsson** [comment]
Three new packages (version 1.2.0) are now uploaded to Episerver NuGet feed, so now we just have to wait for Episerver to publish them.

**Pull request merged**
