### PR TITLE
added criterion

### LINKED ISSUE #25: Add Category Criterion
Added a category criterion to choose how many times a category has been visited

### PR DESCRIPTION
**Pull request by lunchin**
Fixes #25

### CODE REVIEW

**Comment by valdisiljuconoks** [comment]
Awesome! ;)

**Comment by MattisOlsson** [comment]
Thanks!

**Comment by MattisOlsson** [comment]
I'm currently uploading version 1.2.10 to EPiServer NuGet feed.

**Comment by fremler** [comment]
I don't know if I'm missing something but my categories doesn't show up in the dropdown list when i select to use a "Visited geta category" in Visitor groups. Do I need to add them manually?

**Comment by jamesjohnsontwentysix** [comment]
@MattisOlsson @lunchin Any plans for this criteria to work with site-level categories rather than just global ones?

**Pull request merged**
